/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dotnative_globalhook_keyboard_GlobalKeyHook */

#ifndef _Included_org_dotnative_globalhook_keyboard_GlobalKeyHook
#define _Included_org_dotnative_globalhook_keyboard_GlobalKeyHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dotnative_globalhook_keyboard_GlobalKeyHook
 * Method:    registerHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dotnative_globalhook_keyboard_GlobalKeyHook_registerHook
  (JNIEnv *, jobject);

/*
 * Class:     org_dotnative_globalhook_keyboard_GlobalKeyHook
 * Method:    unregisterHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dotnative_globalhook_keyboard_GlobalKeyHook_unregisterHook
  (JNIEnv *, jobject);

/*
 * Class:     org_dotnative_globalhook_keyboard_GlobalKeyHook
 * Method:    unregisterHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dotnative_globalhook_keyboard_GlobalKeyHook_startHook
  (JNIEnv *, jobject);

/*
 * Class:     org_dotnative_globalhook_keyboard_GlobalKeyHook
 * Method:    unregisterHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dotnative_globalhook_keyboard_GlobalKeyHook_stopHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
