/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnativegrab_keyboard_GrabKeyHook */

#ifndef _Included_org_jnativegrab_keyboard_GrabKeyHook
#define _Included_org_jnativegrab_keyboard_GrabKeyHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnativegrab_keyboard_GrabKeyHook
 * Method:    registerHook
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_jnativegrab_keyboard_GrabKeyHook_registerHook
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jnativegrab_keyboard_GrabKeyHook
 * Method:    unregisterHook
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_jnativegrab_keyboard_GrabKeyHook_unregisterHook
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_jnativegrab_keyboard_GrabKeyHook
 * Method:    unregisterHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnativegrab_keyboard_GrabKeyHook_startHook
  (JNIEnv *, jobject);

/*
 * Class:     org_jnativegrab_keyboard_GrabKeyHook
 * Method:    unregisterHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnativegrab_keyboard_GrabKeyHook_stopHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
