/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_keyboard_PollThread */

#ifndef _Included_jni_keyboard_PollThread
#define _Included_jni_keyboard_PollThread
#ifdef __cplusplus
extern "C" {
#endif
#undef jni_keyboard_PollThread_MIN_PRIORITY
#define jni_keyboard_PollThread_MIN_PRIORITY 1L
#undef jni_keyboard_PollThread_NORM_PRIORITY
#define jni_keyboard_PollThread_NORM_PRIORITY 5L
#undef jni_keyboard_PollThread_MAX_PRIORITY
#define jni_keyboard_PollThread_MAX_PRIORITY 10L
/*
 * Class:     jni_keyboard_PollThread
 * Method:    checkKeyboardChanges
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_keyboard_PollThread_checkKeyboardChanges
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
