//Refernce: ${JAVA_HOME}/src.zip/java/awt/event/MouseEvent.java

#define JK_MOUSE_FIRST		500
#define JK_MOUSE_LAST		507
#define JK_MOUSE_CLICKED	JK_MOUSE_FIRST
#define JK_MOUSE_PRESSED	1 + JK_MOUSE_FIRST
#define JK_MOUSE_RELEASED	2 + JK_MOUSE_FIRST
#define JK_MOUSE_MOVED		3 + JK_MOUSE_FIRST
#define JK_MOUSE_ENTERED	4 + JK_MOUSE_FIRST
#define JK_MOUSE_EXITED		5 + JK_MOUSE_FIRST
#define JK_MOUSE_DRAGGED	6 + JK_MOUSE_FIRST
#define JK_MOUSE_WHEEL		7 + JK_MOUSE_FIRST
