//Refernce: org/jnativehook/keyboard/NativeKeyEvent.java
#define JK_NATIVE_KEY_FIRST			2400
#define JK_NATIVE_KEY_LAST			2402
#define JK_NATIVE_KEY_TYPED			JK_NATIVE_KEY_FIRST
#define JK_NATIVE_KEY_PRESSED		1 + JK_NATIVE_KEY_FIRST
#define JK_NATIVE_KEY_RELEASED		2 + JK_NATIVE_KEY_FIRST

//Refernce: org/jnativehook/mouse/NativeMouseEvent.java
#define JK_NATIVE_MOUSE_FIRST		2500
#define JK_NATIVE_MOUSE_LAST		2507
#define JK_NATIVE_MOUSE_CLICKED		JK_NATIVE_MOUSE_FIRST
#define JK_NATIVE_MOUSE_PRESSED		1 + JK_NATIVE_MOUSE_FIRST
#define JK_NATIVE_MOUSE_RELEASED	2 + JK_NATIVE_MOUSE_FIRST
#define JK_NATIVE_MOUSE_MOVED		3 + JK_NATIVE_MOUSE_FIRST
#define JK_NATIVE_MOUSE_ENTERED		4 + JK_NATIVE_MOUSE_FIRST
#define JK_NATIVE_MOUSE_EXITED		5 + JK_NATIVE_MOUSE_FIRST
#define JK_NATIVE_MOUSE_DRAGGED		6 + JK_NATIVE_MOUSE_FIRST
#define JK_NATIVE_MOUSE_WHEEL		7 + JK_NATIVE_MOUSE_FIRST
