/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnativehook_GlobalScreen */

#ifndef _Included_org_jnativehook_GlobalScreen
#define _Included_org_jnativehook_GlobalScreen
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnativehook_GlobalScreen_serialVersionUID
#define org_jnativehook_GlobalScreen_serialVersionUID 6504561173380322679LL
/* Inaccessible static: instance */
#ifdef __cplusplus
}
#endif
#endif
