/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnativehook_GlobalScreen */

#ifndef _Included_org_jnativehook_GlobalScreen
#define _Included_org_jnativehook_GlobalScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnativehook_GlobalScreen
 * Method:    registerNativeHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnativehook_GlobalScreen_registerNativeHook
  (JNIEnv *, jclass);

/*
 * Class:     org_jnativehook_GlobalScreen
 * Method:    unregisterNativeHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnativehook_GlobalScreen_unregisterNativeHook
  (JNIEnv *, jclass);

/*
 * Class:     org_jnativehook_GlobalScreen
 * Method:    isNativeHookRegistered
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jnativehook_GlobalScreen_isNativeHookRegistered
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
