/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dotnative_globalkeylistener_PollThread */

#ifndef _Included_org_dotnative_globalkeylistener_PollThread
#define _Included_org_dotnative_globalkeylistener_PollThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_dotnative_globalkeylistener_PollThread_MIN_PRIORITY
#define org_dotnative_globalkeylistener_PollThread_MIN_PRIORITY 1L
#undef org_dotnative_globalkeylistener_PollThread_NORM_PRIORITY
#define org_dotnative_globalkeylistener_PollThread_NORM_PRIORITY 5L
#undef org_dotnative_globalkeylistener_PollThread_MAX_PRIORITY
#define org_dotnative_globalkeylistener_PollThread_MAX_PRIORITY 10L
/*
 * Class:     org_dotnative_globalkeylistener_PollThread
 * Method:    checkKeyboardChanges
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dotnative_globalkeylistener_PollThread_checkKeyboardChanges
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
